FROM centos:7.3.1611

# Used to create a docker image used for building RPMs
RUN yum install -y dnf-plugins-core python3-dnf-plugins-core --nogpgcheck

# RUN yum config-manager --set-enabled powertools

RUN yum install -y cpio file yum install -y rpm-build rpmlint git rsync python3 python3-pip

RUN python3 -m pip install Jinja2 ipython

